#!/usr/bin/env bash

echo "PATHS: Creating Directories..."
  mkdir -p ~/code/
  mkdir -p ~/script/

echo "SSH Key: Checking for SSH key, generating one if it doesn't exist..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "SSH Key: Copying public key to clipboard. Paste it into your Github and Codeplane account..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh
  open https://codeplane.com/account

echo "Homebrew: Installing an OS X package manager..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/gist/323731)"
  brew update

echo "Homebrew: Setting location earlier in PATH environment variable..."
  echo "
# recommended by brew doctor
export PATH='/usr/local/bin:\$PATH'" >> ~/.zshrc
  source ~/.zshrc

echo "PostgreSQL: Installing an RDBMS..."
  brew install postgres --no-python

echo "PostgreSQL: Creating database..."
  initdb /usr/local/var/postgres

echo "PostgreSQL: Generating manual start/stop script..."
  echo "pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start" > ~/script/postgres_start.sh
  echo "pg_ctl -D /usr/local/var/postgres stop -s -m fast" > ~/script/postgres_stop.sh

echo "MongoDB: Installing a NoSQL database..."
  brew install mongodb

echo "MongoDB: Generating manual start script..."
  echo "mongod run --config /usr/local/Cellar/mongodb/2.0.2-x86_64/mongod.conf" > ~/script/mongodb_start.sh

echo "ack: Installing a grep alternative..."
  brew install ack

echo "tmux: Installing a terminal multiplexer..."
  brew install tmux

echo "ImageMagick: Installing an image processor..."
  brew install imagemagick

echo "QT: Installing dependency of Capybara Webkit for headless Javascript integration testing ..."
  brew install qt

echo "wget: Installing wget..."
  brew install wget

echo "MacVim: Installing an awesome text editor..."
  brew install macvim

echo "Janus: Carlhuda's vim Distribution..."
  curl https://raw.github.com/carlhuda/janus/master/bootstrap.sh -o - | sh

echo "ZSH: OH MY ZSHELL..."
  curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

echo "RVM: Installing ruby version manager..."
  curl -s https://rvm.beginrescueend.com/install/rvm -o rvm-installer ; chmod +x rvm-installer ; ./rvm-installer --version latest
  echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.zshrc
  source ~/.zshrc

echo "Ruby: Beginning installation of ruby..."
  bash < <(curl -s https://raw.github.com/InnoHub/laptop/master/ruby)

echo "Git Settings: Setting up Global gitignore file..."
  git config --global core.excludesfile ~/.gitignore
  echo ".DS_Store" >> ~/.gitignore
  echo "._*" >> ~/.gitignore
  echo ".Spotlight-V100" >> ~/.gitignore
  echo ".Trashes" >> ~/.gitignore

echo "Git Settings: autocrlf and safecrlf"
  git config --global core.autocrlf input
  git config --global core.safecrlf true

echo "Git Settings: Setup aliases..."
  echo "[alias]
  co = checkout
  ci = commit
  st = status
  br = branch
  hist = log --pretty=format:\"%h %ad | %s%d [%an]\" --graph --date=short
  type = cat-file -t
  dump = cat-file -p" >> ~/.gitconfig

echo "Vim Colors: Changing Theme to Solarized..."
  echo "color solarized" > ~/.vimrc.local
  echo "color solarized" > ~/.gvimrc.local

echo "Terminal Colors: Changing Theme to Solarized..."
  wget "https://github.com/tomislav/osx-lion-terminal.app-colors-solarized/raw/master/Solarized%20Dark.terminal"
  open "Solarized Dark.terminal"

  wget "https://github.com/tomislav/osx-lion-terminal.app-colors-solarized/raw/dcdf6d2c1574318dee3a5f641c9b1c6ead19ce74/Solarized%20Light.terminal"
  open "Solarized Light.terminal"

  rm "Solarized Dark.terminal"
  rm "Solarized Light.terminal"

  echo "Downloaded Solarized Themes, please set them as your default theme..."
  echo "You might also want to change the setting: When shell exits to Close if shell exited cleanly under the Terminal Preferences tab..."
