#!/usr/bin/env bash

echo "PATHS: Creating Directories..."
  mkdir -p ~/code/
  mkdir -p ~/script/

echo "SSH Key: Checking for SSH key, generating one if it doesn't exist..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "SSH Key: Copying public key to clipboard. Paste it into your Github and Codeplane account..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh
  open https://codeplane.com/account

echo "Homebrew: Installing an OS X package manager..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/gist/323731)"
  brew update

echo "Homebrew: Setting location earlier in PATH environment variable..."
  echo "
# recommended by brew doctor
export PATH='/usr/local/bin:\$PATH'" >> ~/.zshrc
  source ~/.zshrc

echo "PostgreSQL: Installing an RDBMS..."
  brew install postgres --no-python

echo "PostgreSQL: Creating database..."
  initdb /usr/local/var/postgres

echo "PostgreSQL: Generating manual start/stop script..."
  echo "pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start" > ~/script/postgres_start.sh
  echo "pg_ctl -D /usr/local/var/postgres stop -s -m fast" > ~/script/postgres_stop.sh

echo "MongoDB: Installing a NoSQL database..."
  brew install mongodb

echo "MongoDB: Generating manual start script..."
  echo "mongod run --config /usr/local/Cellar/mongodb/2.0.2-x86_64/mongod.conf" > ~/script/mongodb_start.sh

echo "ack: Installing a grep alternative..."
  brew install ack

echo "tmux: Installing a terminal multiplexer..."
  brew install tmux

echo "ImageMagick: Installing an image processor..."
  brew install imagemagick

echo "QT: Installing dependency of Capybara Webkit for headless Javascript integration testing ..."
  brew install qt
